version: "2"
run:
    timeout: 2m
linters:
    disable:
      - staticcheck
      - unused
    enable:
#    - errcheck
#    - gosimple
#    - govet
#    - ineffassign
    - bodyclose
    - gocheckcompilerdirectives
    - godox
#    - gosec
#    - whitespace
#    - usestdlibvars
formatters:
  enable:
    - gofmt
    - goimports
