run:
    timeout: 2m
linters:
    disable-all: true
    enable:
#    - errcheck
#    - gosimple
#    - govet
#    - ineffassign
#    - staticcheck
#    - unused
    - bodyclose
    - gocheckcompilerdirectives
    - godox
#    - gofmt
#    - goimports
#    - gosec
#    - whitespace
#    - usestdlibvars
