checks:
  go: true
build:
  environment:
    go:
      version: 'go1.17'
    variables:
      GO_ENV: test

  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run

filter:
  excluded_paths:
    - "*_test.go"
    - "*_fixtures_test.go"
