version: "3"

services:
  test:
    build: .
    environment:
      AWS_ENDPOINT: dynamo:8000
      AWS_DEFAULT_REGION: us-east-1
      AWS_DISABLE_SSL: "true"
      API_KEY_TABLE: ApiKey
      WEBAUTHN_TABLE: WebAuthn
      LAMBDA_ROLE: placeholder
    depends_on:
      - dynamo

  app:
    build: .
    working_dir: /src

  dynamo:
    image: amazon/dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: abc123
      AWS_SECRET_ACCESS_KEY: abc123
      AWS_DEFAULT_REGION: us-east-1
    command: "-jar DynamoDBLocal.jar -sharedDb"
