service: twosv-api

frameworkVersion: ^3.7

provider:
  name: aws
  runtime: go1.x
  timeout: 5 # API Gateway invoked functions are limited to 30 seconds
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true

  environment:
    stage: ${sls:stage}
    namespace: ${self:service}_${sls:stage}
    API_KEY_TABLE: ${env:API_KEY_TABLE, "api-key"}
    WEBAUTHN_TABLE: ${env:WEBAUTHN_TABLE, "webauthn"}

  stackTags:
    app: ${self:service}
    app_name: ${self:service}
    app_env: ${sls:stage}

  iam:
    role: ${env:LAMBDA_ROLE}

package:
  patterns:
    - '!./**'
    - './bin/**'

functions:
  webauthn:
    handler: bin/webauthn
    events:
      - http:
          path: '{webauthn+}'
          method: any
