# For full config options, check the docs:
#    docs.serverless.com

service: mfa-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x
  timeout: 5 # API Gateway invoked functions are limited to 30 seconds
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    shouldStartNameWithService: true
  apiKeys:
    - ${self:custom.namespace}-global

  # you can define service wide environment variables here
  environment:
    stage: ${self:custom.stage}
    namespace: ${self:custom.namespace}
    API_KEY_TABLE: ${env:API_KEY_TABLE, "api-key"}
    WEBAUTHN_TABLE: ${env:WEBAUTHN_TABLE, "webauthn"}

  stackTags:
    app: mfa-api
    app_name: mfa-api
    app_env: ${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.namespace}_*"

custom:
  stage: ${opt:stage, self:provider.stage}
  namespace: ${self:service}_${self:custom.stage}
  apiKeyTable: ${self:custom.namespace}_api-key
  webauthnTable: ${self:custom.namespace}_webauthn

package:
  exclude:
    - ./**
  include:
    - bin/**

functions:
  webauthn:
    handler: bin/webauthn
    events:
      - http:
          path: '{webauthn+}'
          method: any
          private: true

resources:
  Resources:
    ApiKeyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: value
            AttributeType: S
        KeySchema:
          - AttributeName: value
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.apiKeyTable}
    WebAuthnDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.webauthnTable}