name: Deploy

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    name: Deploy to AWS Lambda
    needs: tests
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      STG_AWS_ACCESS_KEY_ID: ${{ vars.STG_AWS_ACCESS_KEY_ID }}
      STG_AWS_SECRET_ACCESS_KEY: ${{ secrets.STG_AWS_SECRET_ACCESS_KEY }}
      STG_LAMBDA_ROLE: ${{ vars.STG_LAMBDA_ROLE }}
      STG_API_KEY_TABLE: ${{ vars.STG_API_KEY_TABLE }}
      STG_WEBAUTHN_TABLE: ${{ vars.STG_WEBAUTHN_TABLE }}
      PRD_AWS_ACCESS_KEY_ID: ${{ vars.PRD_AWS_ACCESS_KEY_ID }}
      PRD_AWS_SECRET_ACCESS_KEY: ${{ secrets.PRD_AWS_SECRET_ACCESS_KEY }}
      PRD_LAMBDA_ROLE: ${{ vars.PRD_LAMBDA_ROLE }}
      PRD_API_KEY_TABLE: ${{ vars.PRD_API_KEY_TABLE }}
      PRD_WEBAUTHN_TABLE: ${{ vars.PRD_WEBAUTHN_TABLE }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Deploy
      run: docker-compose -f actions-services.yml run --rm app ./scripts/deploy.sh
